import { Inter } from "next/font/google";
import "./globals.css";
import { AppProvider } from "./components/AppContext";
import Header from "./components/layout/Header";
import "remixicon/fonts/remixicon.css";
import Footer from "./components/layout/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Fashion Fusion",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <main className=" max-w-7xl mx-auto p-4">
                    <AppProvider>
                        <Header />
                        <AppProvider>{children}</AppProvider>
                        <Footer />
                    </AppProvider>
                </main>
            </body>
        </html>
    );
}
