import "./globals.css";
import "remixicon/fonts/remixicon.css";
import { Inter } from "next/font/google";
import { AppProvider } from "./components/AppContext";
import Header from "./components/layout/Header";
import Footer from "./components/layout/Footer";
import { Toaster } from "react-hot-toast";
import ClientLayout from "./client-layout";
import { Suspense } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Fashion Fusion",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className=" max-w-7xl mx-auto p-4">
          {/* <AppProvider>
            <Header />
            {children}
            <Footer />
            <Toaster position="bottom-right" />
          </AppProvider> */}
          <ClientLayout>
            <Suspense fallback={<div>Loading...</div>}>{children}</Suspense>
          </ClientLayout>
        </main>
      </body>
    </html>
  );
}
